$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: diabetesdeployment1
endpoint_name: diabetesend
model: azureml:diabetes_model@latest
environment: azureml:pkg-model1-v1@latest
instance_type: Standard_F2s_v2
instance_count: 1
data_collector:
  collections:
    model_inputs:
      enabled: 'True'
    model_outputs:
      enabled: 'True'
