$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: main2.py
command: >-
  python main2.py 
  --diabetes-csv ${{inputs.diabetes}}
inputs:
  diabetes:
    path: azureml:diabetes-prod:1
    mode: ro_mount
environment: azureml:env1@latest
compute: azureml:cluster707
experiment_name: diabetes-data-example
description: Train a classification model on diabetes data using a registered dataset as input.